main: com.puddingkc.AnvilColorizer
name: AnvilColorizer
version: 1.0.1
api-version: 1.16
author: 'PuddingKC'
permissions:
  anvilcolorizer.use:
    default: op
  anvilcolorizer.use.hex:
    default: op